// <auto-generated />
namespace TPV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Primera10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Primera10));
        
        string IMigrationMetadata.Id
        {
            get { return "201512232038232_Primera10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
